// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

//! Calculator module - expression calculation core
//!
//! Provides calculation functions for both standard and bitwise modes.

use crate::evaluator::{eval_postfix, eval_postfix_bitwise};
use crate::linked_list::LinkedList;
use crate::shunting_yard::{infix_to_postfix, infix_to_postfix_bitwise};
use crate::token::{resolve_constants, tokenize};

/// Calculate expression in standard mode (floating point)
pub fn calculate(expression: &str) -> Result<f64, String> {
    let tokens = tokenize(expression, false);
    let tokens = resolve_constants(tokens);

    let mut list = LinkedList::new();
    for token in tokens {
        list.push_back(token);
    }

    let postfix = infix_to_postfix(list.to_vec());
    eval_postfix(postfix)
}

/// Calculate expression in bitwise mode (integer)
pub fn calculate_bitwise(expression: &str) -> Result<i64, String> {
    let tokens = tokenize(expression, true);
    let tokens = resolve_constants(tokens);

    let mut list = LinkedList::new();
    for token in tokens {
        list.push_back(token);
    }

    let postfix = infix_to_postfix_bitwise(list.to_vec());
    eval_postfix_bitwise(postfix)
}
