// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "ralqlator")]
#[command(about = "A powerful command-line calculator")]
#[command(long_about = "Ralqlator is a feature-rich calculator supporting arithmetic, \
    bitwise operations, mathematical functions, and multiple number formats.")]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Commands>,

    /// Expression to calculate
    #[arg(value_name = "EXPR")]
    pub expression: Option<String>,

    /// Expression to calculate (shorthand)
    #[arg(short = 'r', long = "row", value_name = "EXPR")]
    pub row: Option<String>,

    /// Output result in hexadecimal format
    #[arg(short = 'x', long = "hex")]
    pub hex: bool,

    /// Output result in octal format
    #[arg(short = 'o', long = "oct")]
    pub oct: bool,

    /// Output result in binary format
    #[arg(short = 'b', long = "bin")]
    pub bin: bool,

    /// Bitwise operation mode
    #[arg(short = 'B', long = "bits")]
    pub bits: bool,

    /// Show help for functions
    #[arg(short = 'F', long = "functions", action = clap::ArgAction::SetTrue)]
    pub show_functions: bool,

    /// Show help for operators
    #[arg(short = 'O', long = "operators", action = clap::ArgAction::SetTrue)]
    pub show_operators: bool,

    /// Show help for number formats
    #[arg(short = 'N', long = "formats", action = clap::ArgAction::SetTrue)]
    pub show_formats: bool,

    /// Show help for constants
    #[arg(short = 'C', long = "constants", action = clap::ArgAction::SetTrue)]
    pub show_constants: bool,
}

#[derive(Subcommand)]
pub enum Commands {
    /// Show supported mathematical functions
    Functions,
    /// Show supported operators
    Operators,
    /// Show supported number formats
    Formats,
    /// Show mathematical constants
    Constants,
    /// Show all help information
    Info,
}
