// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

/// User-defined function storage
/// Maps function name -> (parameter names, expression)
pub type UserFunctions = Arc<Mutex<HashMap<String, (Vec<String>, String)>>>;

/// Calculate factorial: n! = n * (n-1) * ... * 1
pub fn eval_factorial(n: f64) -> Result<f64, String> {
    if n < 0.0 {
        return Err("factorial: argument must be non-negative".to_string());
    }
    if n.fract() != 0.0 {
        return Err("factorial: argument must be an integer".to_string());
    }
    if n > 170.0 {
        return Err("factorial: argument too large (max 170)".to_string());
    }
    let n = n as u64;
    let mut result = 1.0;
    for i in 2..=n {
        result *= i as f64;
    }
    Ok(result)
}

/// Calculate sum of multiple arguments: sum(a, b, c, ...) = a + b + c + ...
pub fn eval_sum(args: &[f64]) -> Result<f64, String> {
    if args.is_empty() {
        return Err("sum: requires at least 1 argument".to_string());
    }
    Ok(args.iter().sum())
}

/// Calculate product of multiple arguments: prod(a, b, c, ...) = a * b * c * ...
pub fn eval_product(args: &[f64]) -> Result<f64, String> {
    if args.is_empty() {
        return Err("prod: requires at least 1 argument".to_string());
    }
    Ok(args.iter().product())
}

/// Calculate logarithm with custom base: log_base(base, x) = ln(x) / ln(base)
pub fn eval_log_base(base: f64, x: f64) -> Result<f64, String> {
    if base <= 0.0 || base == 1.0 {
        return Err("log: base must be positive and not equal to 1".to_string());
    }
    if x <= 0.0 {
        return Err("log: argument must be positive".to_string());
    }
    Ok(x.ln() / base.ln())
}

/// Evaluate lg (base 10 logarithm)
pub fn eval_lg(x: f64) -> Result<f64, String> {
    if x <= 0.0 {
        return Err("lg: argument must be positive".to_string());
    }
    Ok(x.log10())
}

/// Evaluate ln (natural logarithm)
pub fn eval_ln(x: f64) -> Result<f64, String> {
    if x <= 0.0 {
        return Err("ln: argument must be positive".to_string());
    }
    Ok(x.ln())
}

/// Evaluate sqrt (square root)
pub fn eval_sqrt(x: f64) -> Result<f64, String> {
    if x < 0.0 {
        return Err("sqrt: argument must be non-negative".to_string());
    }
    Ok(x.sqrt())
}

/// Evaluate pow (power function)
pub fn eval_pow(base: f64, exp: f64) -> Result<f64, String> {
    Ok(base.powf(exp))
}

/// Evaluate sin (sine function, input in radians)
pub fn eval_sin(x: f64) -> f64 {
    x.sin()
}

/// Evaluate cos (cosine function, input in radians)
pub fn eval_cos(x: f64) -> f64 {
    x.cos()
}

/// Evaluate tan (tangent function, input in radians)
pub fn eval_tan(x: f64) -> Result<f64, String> {
    // Check for undefined values (cos(x) == 0)
    if x.cos() == 0.0 {
        return Err("tan: undefined at this value".to_string());
    }
    Ok(x.tan())
}

/// Evaluate asin (inverse sine function, output in radians)
pub fn eval_asin(x: f64) -> Result<f64, String> {
    if !(-1.0..=1.0).contains(&x) {
        return Err("asin: argument must be in range [-1, 1]".to_string());
    }
    Ok(x.asin())
}

/// Evaluate acos (inverse cosine function, output in radians)
pub fn eval_acos(x: f64) -> Result<f64, String> {
    if !(-1.0..=1.0).contains(&x) {
        return Err("acos: argument must be in range [-1, 1]".to_string());
    }
    Ok(x.acos())
}

/// Evaluate atan (inverse tangent function, output in radians)
pub fn eval_atan(x: f64) -> f64 {
    x.atan()
}

/// Evaluate mod (modulo function)
pub fn eval_mod(a: f64, b: f64) -> Result<f64, String> {
    if b == 0.0 {
        return Err("mod: modulo by zero".to_string());
    }
    Ok(a % b)
}
