// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

#![allow(dead_code)]

mod calculator;
mod cli;
mod evaluator;
mod functions;
mod operator;
mod repl;
mod shunting_yard;
mod token;

#[cfg(test)]
mod tests {
    use super::*;

    // ==================== Basic Arithmetic Tests ====================

    #[test]
    fn test_addition() {
        assert_eq!(calculator::calculate("1 + 2").unwrap(), 3.0);
        assert_eq!(calculator::calculate("10 + 20").unwrap(), 30.0);
        assert_eq!(calculator::calculate("-5 + 3").unwrap(), -2.0);
    }

    #[test]
    fn test_subtraction() {
        assert_eq!(calculator::calculate("10 - 3").unwrap(), 7.0);
        assert_eq!(calculator::calculate("5 - 10").unwrap(), -5.0);
    }

    #[test]
    fn test_multiplication() {
        assert_eq!(calculator::calculate("3 * 4").unwrap(), 12.0);
        assert_eq!(calculator::calculate("-2 * 3").unwrap(), -6.0);
    }

    #[test]
    fn test_division() {
        assert_eq!(calculator::calculate("10 / 2").unwrap(), 5.0);
        assert_eq!(calculator::calculate("7 / 2").unwrap(), 3.5);
    }

    #[test]
    fn test_division_by_zero() {
        assert!(calculator::calculate("10 / 0").is_err());
    }

    #[test]
    fn test_modulo() {
        assert_eq!(calculator::calculate("10 % 3").unwrap(), 1.0);
        assert_eq!(calculator::calculate("17 % 5").unwrap(), 2.0);
    }

    #[test]
    fn test_modulo_by_zero() {
        assert!(calculator::calculate("10 % 0").is_err());
    }

    #[test]
    fn test_exponentiation() {
        assert_eq!(calculator::calculate("2 ^ 3").unwrap(), 8.0);
        assert_eq!(calculator::calculate("2 ^ 10").unwrap(), 1024.0);
    }

    #[test]
    fn test_operator_precedence() {
        assert_eq!(calculator::calculate("1 + 2 * 3").unwrap(), 7.0);
        assert_eq!(calculator::calculate("(1 + 2) * 3").unwrap(), 9.0);
        assert_eq!(calculator::calculate("2 + 3 * 4 - 5").unwrap(), 9.0);
    }

    // ==================== Number Format Tests ====================

    #[test]
    fn test_binary_input() {
        assert_eq!(calculator::calculate("0b1010").unwrap(), 10.0);
        assert_eq!(calculator::calculate("0b11111111").unwrap(), 255.0);
    }

    #[test]
    fn test_octal_input() {
        assert_eq!(calculator::calculate("0o755").unwrap(), 493.0);
        assert_eq!(calculator::calculate("0o10").unwrap(), 8.0);
    }

    #[test]
    fn test_hexadecimal_input() {
        assert_eq!(calculator::calculate("0xFF").unwrap(), 255.0);
        assert_eq!(calculator::calculate("0x10").unwrap(), 16.0);
        assert_eq!(calculator::calculate("0x1A").unwrap(), 26.0);
    }

    #[test]
    fn test_scientific_notation() {
        assert_eq!(calculator::calculate("1e3").unwrap(), 1000.0);
        assert_eq!(calculator::calculate("2.5e-3").unwrap(), 0.0025);
        assert_eq!(calculator::calculate("1.23E+10").unwrap(), 12300000000.0);
    }

    // ==================== Constants Tests ====================

    #[test]
    fn test_pi_constant() {
        let result = calculator::calculate("pi").unwrap();
        assert!((result - std::f64::consts::PI).abs() < 1e-10);
    }

    #[test]
    fn test_e_constant() {
        let result = calculator::calculate("e").unwrap();
        assert!((result - std::f64::consts::E).abs() < 1e-10);
    }

    #[test]
    fn test_pi_case_insensitive() {
        assert_eq!(calculator::calculate("pi").unwrap(), calculator::calculate("PI").unwrap());
    }

    // ==================== Function Tests ====================

    #[test]
    fn test_lg_base10() {
        assert_eq!(calculator::calculate("lg(100)").unwrap(), 2.0);
        assert_eq!(calculator::calculate("lg(1000)").unwrap(), 3.0);
    }

    #[test]
    fn test_lg_custom_base() {
        assert_eq!(calculator::calculate("lg(8, 2)").unwrap(), 3.0);
        assert_eq!(calculator::calculate("lg(1024, 2)").unwrap(), 10.0);
    }

    #[test]
    fn test_log_custom_base() {
        assert_eq!(calculator::calculate("log(8, 2)").unwrap(), 3.0);
        assert_eq!(calculator::calculate("log(27, 3)").unwrap(), 3.0);
    }

    #[test]
    fn test_ln() {
        let result = calculator::calculate("ln(e)").unwrap();
        assert!((result - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_sqrt() {
        assert_eq!(calculator::calculate("sqrt(16)").unwrap(), 4.0);
        assert_eq!(calculator::calculate("sqrt(2)").unwrap(), 2.0_f64.sqrt());
    }

    #[test]
    fn test_pow() {
        assert_eq!(calculator::calculate("pow(2, 10)").unwrap(), 1024.0);
        assert_eq!(calculator::calculate("pow(3, 3)").unwrap(), 27.0);
    }

    #[test]
    fn test_mod_function() {
        assert_eq!(calculator::calculate("mod(10, 3)").unwrap(), 1.0);
        assert_eq!(calculator::calculate("mod(17, 5)").unwrap(), 2.0);
    }

    // ==================== Trigonometric Tests ====================

    #[test]
    fn test_sin() {
        assert!(calculator::calculate("sin(0)").unwrap().abs() < 1e-10);
        assert!((calculator::calculate("sin(pi / 2)").unwrap() - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_cos() {
        assert_eq!(calculator::calculate("cos(0)").unwrap(), 1.0);
        assert!(calculator::calculate("cos(pi)").unwrap().abs() - 1.0 < 1e-10);
    }

    #[test]
    fn test_tan() {
        assert!(calculator::calculate("tan(0)").unwrap().abs() < 1e-10);
    }

    #[test]
    fn test_asin() {
        let result = calculator::calculate("asin(1)").unwrap();
        assert!((result - std::f64::consts::PI / 2.0).abs() < 1e-10);
    }

    #[test]
    fn test_acos() {
        let result = calculator::calculate("acos(1)").unwrap();
        assert!(result.abs() < 1e-10);
    }

    #[test]
    fn test_atan() {
        let result = calculator::calculate("atan(1)").unwrap();
        assert!((result - std::f64::consts::PI / 4.0).abs() < 1e-10);
    }

    // ==================== Bitwise Tests ====================

    #[test]
    fn test_bitwise_and() {
        assert_eq!(calculator::calculate_bitwise("12 & 10").unwrap(), 8);
        assert_eq!(calculator::calculate_bitwise("0xFF & 0x0F").unwrap(), 0x0F);
    }

    #[test]
    fn test_bitwise_or() {
        assert_eq!(calculator::calculate_bitwise("12 | 10").unwrap(), 14);
        assert_eq!(calculator::calculate_bitwise("0xF0 | 0x0F").unwrap(), 0xFF);
    }

    #[test]
    fn test_bitwise_xor() {
        assert_eq!(calculator::calculate_bitwise("12 ^ 10").unwrap(), 6);
        assert_eq!(calculator::calculate_bitwise("0xFF ^ 0x0F").unwrap(), 0xF0);
    }

    #[test]
    fn test_bitwise_not() {
        assert_eq!(calculator::calculate_bitwise("~0").unwrap(), -1);
        assert_eq!(calculator::calculate_bitwise("~12").unwrap(), -13);
    }

    #[test]
    fn test_left_shift() {
        assert_eq!(calculator::calculate_bitwise("8 << 2").unwrap(), 32);
        assert_eq!(calculator::calculate_bitwise("1 << 10").unwrap(), 1024);
    }

    #[test]
    fn test_right_shift() {
        assert_eq!(calculator::calculate_bitwise("8 >> 2").unwrap(), 2);
        assert_eq!(calculator::calculate_bitwise("1024 >> 10").unwrap(), 1);
    }

    #[test]
    fn test_invalid_shift() {
        assert!(calculator::calculate_bitwise("8 << 64").is_err());
        assert!(calculator::calculate_bitwise("8 >> -1").is_err());
    }

    #[test]
    fn test_bitwise_mixed_formats() {
        assert_eq!(calculator::calculate_bitwise("0b1010 & 0xFF").unwrap(), 10);
        assert_eq!(calculator::calculate_bitwise("0o10 | 0x0F").unwrap(), 15);
    }

    // ==================== Error Handling Tests ====================

    #[test]
    fn test_invalid_number() {
        assert!(calculator::calculate("abc").is_err());
    }

    #[test]
    fn test_invalid_function() {
        assert!(calculator::calculate("invalid(1)").is_err());
    }

    #[test]
    fn test_division_by_zero_error_message() {
        let err = calculator::calculate("10 / 0").unwrap_err();
        assert!(err.contains("Division by zero"));
    }

    #[test]
    fn test_asin_domain_error() {
        assert!(calculator::calculate("asin(2)").is_err());
        assert!(calculator::calculate("asin(-2)").is_err());
    }

    #[test]
    fn test_sqrt_negative_error() {
        assert!(calculator::calculate("sqrt(-1)").is_err());
    }

    #[test]
    fn test_ln_negative_error() {
        assert!(calculator::calculate("ln(-1)").is_err());
        assert!(calculator::calculate("ln(0)").is_err());
    }

    // ==================== Tokenizer Tests ====================

    #[test]
    fn test_tokenize_simple() {
        let tokens = token::tokenize("1 + 2", false);
        assert_eq!(tokens, vec!["1", "+", "2"]);
    }

    #[test]
    fn test_tokenize_with_parentheses() {
        let tokens = token::tokenize("(1 + 2) * 3", false);
        assert_eq!(tokens, vec!["(", "1", "+", "2", ")", "*", "3"]);
    }

    #[test]
    fn test_tokenize_function() {
        let tokens = token::tokenize("sin(pi)", false);
        assert_eq!(tokens, vec!["sin", "(", "pi", ")"]);
    }

    #[test]
    fn test_tokenize_bitwise() {
        let tokens = token::tokenize("12 & 10", true);
        assert_eq!(tokens, vec!["12", "&", "10"]);
    }

    #[test]
    fn test_tokenize_shift() {
        let tokens = token::tokenize("8 << 2", true);
        assert_eq!(tokens, vec!["8", "<<", "2"]);
    }

    // ==================== Shunting Yard Tests ====================

    #[test]
    fn test_infix_to_postfix_simple() {
        let tokens = vec!["1".to_string(), "+".to_string(), "2".to_string()];
        let postfix = shunting_yard::infix_to_postfix(tokens);
        assert_eq!(postfix, vec!["1", "2", "+"]);
    }

    #[test]
    fn test_infix_to_postfix_precedence() {
        let tokens = vec!["1".to_string(), "+".to_string(), "2".to_string(), "*".to_string(), "3".to_string()];
        let postfix = shunting_yard::infix_to_postfix(tokens);
        assert_eq!(postfix, vec!["1", "2", "3", "*", "+"]);
    }

    #[test]
    fn test_infix_to_postfix_parentheses() {
        let tokens = vec!["(".to_string(), "1".to_string(), "+".to_string(), "2".to_string(), ")".to_string(), "*".to_string(), "3".to_string()];
        let postfix = shunting_yard::infix_to_postfix(tokens);
        assert_eq!(postfix, vec!["1", "2", "+", "3", "*"]);
    }

    // ==================== Output Format Tests ====================

    #[test]
    fn test_negative_hex_output() {
        // Test the format logic directly
        let val: i64 = -255;
        let hex = format!("-0x{:X}", val.unsigned_abs());
        assert_eq!(hex, "-0xFF");
    }

    #[test]
    fn test_negative_octal_output() {
        let val: i64 = -64;
        let oct = format!("-0o{:o}", val.unsigned_abs());
        assert_eq!(oct, "-0o100");
    }

    #[test]
    fn test_negative_binary_output() {
        let val: i64 = -8;
        let bin = format!("-0b{:b}", val.unsigned_abs());
        assert_eq!(bin, "-0b1000");
    }

    // ==================== Integration Tests ====================

    #[test]
    fn test_complex_expression() {
        let result = calculator::calculate("sin(pi / 2) + cos(0)").unwrap();
        assert!((result - 2.0).abs() < 1e-10);
    }

    #[test]
    fn test_nested_functions() {
        let result = calculator::calculate("sqrt(pow(3, 2) + pow(4, 2))").unwrap();
        assert!((result - 5.0).abs() < 1e-10);
    }

    #[test]
    fn test_log_with_pi() {
        let result = calculator::calculate("lg(pi * 10)").unwrap();
        let expected = (std::f64::consts::PI * 10.0).log10();
        assert!((result - expected).abs() < 1e-10);
    }

    #[test]
    fn test_bitwise_complex() {
        let result = calculator::calculate_bitwise("(0xFF & 0xF0) | (0x0F & 0x0F)").unwrap();
        assert_eq!(result, 0xFF);
    }

    #[test]
    fn test_mixed_arithmetic_bitwise() {
        // Standard mode with hex input
        let result = calculator::calculate("0xFF + 1").unwrap();
        assert_eq!(result, 256.0);
    }

    // ==================== Factorial Tests ====================

    #[test]
    fn test_factorial_zero() {
        assert_eq!(calculator::calculate("factorial(0)").unwrap(), 1.0);
    }

    #[test]
    fn test_factorial_one() {
        assert_eq!(calculator::calculate("factorial(1)").unwrap(), 1.0);
    }

    #[test]
    fn test_factorial_large() {
        let result = calculator::calculate("factorial(10)").unwrap();
        assert_eq!(result, 3628800.0);
    }

    #[test]
    fn test_factorial_negative() {
        assert!(calculator::calculate("factorial(-1)").is_err());
    }

    #[test]
    fn test_factorial_non_integer() {
        assert!(calculator::calculate("factorial(3.5)").is_err());
    }

    #[test]
    fn test_factorial_too_large() {
        assert!(calculator::calculate("factorial(171)").is_err());
    }

    // ==================== Sum Function Tests ====================

    #[test]
    fn test_sum_single() {
        assert_eq!(calculator::calculate("sum(5)").unwrap(), 5.0);
    }

    #[test]
    fn test_sum_multiple() {
        assert_eq!(calculator::calculate("sum(1,2,3,4,5)").unwrap(), 15.0);
    }

    #[test]
    fn test_sum_float() {
        assert!((calculator::calculate("sum(1.5,2.5,3)").unwrap() - 7.0).abs() < 1e-10);
    }

    #[test]
    fn test_sum_empty() {
        assert!(calculator::calculate("sum()").is_err());
    }

    // ==================== Product Function Tests ====================

    #[test]
    fn test_prod_single() {
        assert_eq!(calculator::calculate("prod(5)").unwrap(), 5.0);
    }

    #[test]
    fn test_prod_multiple() {
        assert_eq!(calculator::calculate("prod(1,2,3,4,5)").unwrap(), 120.0);
    }

    #[test]
    fn test_prod_float() {
        assert!((calculator::calculate("prod(1.5,2,3)").unwrap() - 9.0).abs() < 1e-10);
    }

    #[test]
    fn test_prod_empty() {
        assert!(calculator::calculate("prod()").is_err());
    }

    #[test]
    fn test_prod_with_zero() {
        assert_eq!(calculator::calculate("prod(1,2,0,4)").unwrap(), 0.0);
    }

    // ==================== User-defined Function Tests ====================

    #[test]
    fn test_user_function_simple() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("f".to_string(), (vec!["x".to_string()], "x^2".to_string()));
        }

        let result = calculate_with_functions("f(5)", &user_functions).unwrap();
        assert_eq!(result, 25.0);
    }

    #[test]
    fn test_user_function_two_args() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("add".to_string(), (vec!["a".to_string(), "b".to_string()], "a+b".to_string()));
        }

        let result = calculate_with_functions("add(3, 7)", &user_functions).unwrap();
        assert_eq!(result, 10.0);
    }

    #[test]
    fn test_user_function_wrong_args() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("f".to_string(), (vec!["x".to_string(), "y".to_string()], "x+y".to_string()));
        }

        // Wrong number of arguments
        assert!(calculate_with_functions("f(5)", &user_functions).is_err());
    }

    // ==================== Sequence Sum (suma) Tests ====================

    #[test]
    fn test_suma_triangle() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("triangle".to_string(), (vec!["n".to_string()], "n*(n+1)/2".to_string()));
        }

        // Sum of first 5 triangle numbers: 1+3+6+10+15 = 35
        let result = calculate_with_functions("suma(triangle, 1, 5)", &user_functions).unwrap();
        assert_eq!(result, 35.0);
    }

    #[test]
    fn test_suma_square() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("square".to_string(), (vec!["n".to_string()], "n^2".to_string()));
        }

        // Sum of first 5 squares: 1+4+9+16+25 = 55
        let result = calculate_with_functions("suma(square, 1, 5)", &user_functions).unwrap();
        assert_eq!(result, 55.0);
    }

    #[test]
    fn test_suma_invalid_begin() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("seq".to_string(), (vec!["n".to_string()], "n".to_string()));
        }

        assert!(calculate_with_functions("suma(seq, 0, 5)", &user_functions).is_err());
        assert!(calculate_with_functions("suma(seq, -1, 5)", &user_functions).is_err());
    }

    #[test]
    fn test_suma_invalid_end() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("seq".to_string(), (vec!["n".to_string()], "n".to_string()));
        }

        assert!(calculate_with_functions("suma(seq, 1, 0)", &user_functions).is_err());
        assert!(calculate_with_functions("suma(seq, 1, -1)", &user_functions).is_err());
    }

    #[test]
    fn test_suma_begin_greater_than_end() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("seq".to_string(), (vec!["n".to_string()], "n".to_string()));
        }

        assert!(calculate_with_functions("suma(seq, 10, 5)", &user_functions).is_err());
    }

    #[test]
    fn test_suma_sequence_not_found() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));

        assert!(calculate_with_functions("suma(unknown, 1, 5)", &user_functions).is_err());
    }

    #[test]
    fn test_suma_wrong_arg_count() {
        use crate::calculator::calculate_with_functions;
        use crate::functions::UserFunctions;
        use std::sync::Arc;
        use std::collections::HashMap;
        use std::sync::Mutex;

        let user_functions: UserFunctions = Arc::new(Mutex::new(HashMap::new()));
        {
            let mut funcs = user_functions.lock().unwrap();
            funcs.insert("seq".to_string(), (vec!["n".to_string()], "n".to_string()));
        }

        assert!(calculate_with_functions("suma(seq, 1)", &user_functions).is_err());
        assert!(calculate_with_functions("suma(seq, 1, 5, 10)", &user_functions).is_err());
    }

    // ==================== Edge Cases ====================

    #[test]
    fn test_double_negative() {
        // Note: --5 is not supported, use parentheses for negation
        assert_eq!(calculator::calculate("0 - (-5)").unwrap(), 5.0);
    }

    #[test]
    fn test_unary_minus_in_expression() {
        assert_eq!(calculator::calculate("-3 + 5").unwrap(), 2.0);
        assert_eq!(calculator::calculate("5 + -3").unwrap(), 2.0);
    }

    #[test]
    fn test_deeply_nested_parens() {
        assert_eq!(calculator::calculate("(((1+2)))").unwrap(), 3.0);
        assert_eq!(calculator::calculate("((2+3)*(4+5))").unwrap(), 45.0);
    }

    #[test]
    fn test_very_small_numbers() {
        let result = calculator::calculate("1e-10 + 1e-10").unwrap();
        assert!((result - 2e-10).abs() < 1e-20);
    }

    #[test]
    fn test_very_large_numbers() {
        let result = calculator::calculate("1e100 * 1e100").unwrap();
        assert!((result - 1e200).abs() < 1e190);
    }

    #[test]
    fn test_division_result_decimal() {
        assert_eq!(calculator::calculate("1/3").unwrap(), 1.0/3.0);
    }

    #[test]
    fn test_power_zero() {
        assert_eq!(calculator::calculate("5^0").unwrap(), 1.0);
        assert_eq!(calculator::calculate("0^5").unwrap(), 0.0);
    }

    #[test]
    fn test_mod_negative() {
        assert_eq!(calculator::calculate("mod(-10, 3)").unwrap(), -1.0);
    }

    #[test]
    fn test_trig_pi_values() {
        assert!(calculator::calculate("sin(pi)").unwrap().abs() < 1e-10);
        assert!((calculator::calculate("cos(pi)").unwrap() + 1.0).abs() < 1e-10);
        assert!(calculator::calculate("tan(pi)").unwrap().abs() < 1e-10);
    }

    #[test]
    fn test_inverse_trig_ranges() {
        assert!(calculator::calculate("asin(0)").unwrap().abs() < 1e-10);
        assert!(calculator::calculate("acos(0)").unwrap().abs() - std::f64::consts::PI/2.0 < 1e-10);
        assert!(calculator::calculate("atan(0)").unwrap().abs() < 1e-10);
    }

    // ==================== Invalid Input Tests ====================

    #[test]
    fn test_invalid_characters() {
        assert!(calculator::calculate("abc").is_err());
        assert!(calculator::calculate("1+abc").is_err());
    }

    #[test]
    fn test_unmatched_parens() {
        // Note: Extra closing paren may not be detected in all cases
        assert!(calculator::calculate("((1+2)").is_err());
        // Opening paren without closing
        assert!(calculator::calculate("(1+2").is_err());
    }

    #[test]
    fn test_empty_expression() {
        assert!(calculator::calculate("").is_err());
    }

    #[test]
    fn test_only_operator() {
        assert!(calculator::calculate("+").is_err());
        assert!(calculator::calculate("*").is_err());
    }

    #[test]
    fn test_consecutive_operators() {
        assert!(calculator::calculate("1++2").is_err());
        assert!(calculator::calculate("1**2").is_err());
    }

    #[test]
    fn test_division_by_zero_in_function() {
        assert!(calculator::calculate("1/0 + 5").is_err());
    }

    #[test]
    fn test_sqrt_negative_in_expression() {
        assert!(calculator::calculate("sqrt(-5)").is_err());
    }

    #[test]
    fn test_log_invalid_base() {
        assert!(calculator::calculate("lg(100, 1)").is_err());
        assert!(calculator::calculate("lg(100, 0)").is_err());
        assert!(calculator::calculate("lg(100, -1)").is_err());
    }

    #[test]
    fn test_function_invalid_args() {
        assert!(calculator::calculate("sin()").is_err());
        assert!(calculator::calculate("pow(2)").is_err());
        assert!(calculator::calculate("pow(2,3,4)").is_err());
    }

    // ==================== Comparison Operator Tests ====================

    #[test]
    fn test_comparison_greater_than() {
        // > returns true/false
        let result = calculator::calculate("5 > 3").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("true".to_string()));
        
        let result = calculator::calculate("3 > 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
        
        let result = calculator::calculate("5 > 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
    }

    #[test]
    fn test_comparison_less_than() {
        // < returns true/false
        let result = calculator::calculate("3 < 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("true".to_string()));
        
        let result = calculator::calculate("5 < 3").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
        
        let result = calculator::calculate("5 < 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
    }

    #[test]
    fn test_comparison_single_equals() {
        // Single = returns special yes/no values
        let result = calculator::calculate("5 = 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("yes".to_string()));
        
        let result = calculator::calculate("5 = 3").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("no".to_string()));
    }

    #[test]
    fn test_comparison_double_equals() {
        // Double == returns special true/false values
        let result = calculator::calculate("5 == 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("true".to_string()));
        
        let result = calculator::calculate("5 == 3").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
    }

    #[test]
    fn test_comparison_with_floats() {
        let result = calculator::calculate("3.14 < 3.15").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("true".to_string()));
        
        let result = calculator::calculate("3.14 > 3.15").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
    }

    #[test]
    fn test_comparison_with_expressions() {
        let result = calculator::calculate("2 + 3 > 4").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("true".to_string()));
        
        let result = calculator::calculate("2 * 3 < 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
        
        let result = calculator::calculate("10 / 2 = 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("yes".to_string()));
    }

    #[test]
    fn test_comparison_precedence() {
        // Comparison should have lowest precedence
        // 2 + 3 > 4 + 1 means (2+3) > (4+1) means 5 > 5 which is false
        let result = calculator::calculate("2 + 3 > 4 + 1").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("false".to_string()));
        
        let result = calculator::calculate("2 + 3 > 3 + 1").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("true".to_string()));
        
        // Single = returns special yes/no value
        let result = calculator::calculate("10 - 5 = 5").unwrap();
        assert!(evaluator::format_comparison_result(result) == Some("yes".to_string()));
    }
}
