// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

/// Linked list node for storing numbers and operators in expressions
#[derive(Debug, Clone)]
pub struct Node {
    pub value: String,
    pub next: Option<Box<Node>>,
}

impl Node {
    pub fn new(value: String) -> Self {
        Node { value, next: None }
    }
}

/// Linked list structure for storing expressions
pub struct LinkedList {
    head: Option<Box<Node>>,
}

impl LinkedList {
    pub fn new() -> Self {
        LinkedList { head: None }
    }

    pub fn push_back(&mut self, value: String) {
        let new_node = Box::new(Node::new(value));
        match self.head {
            None => {
                self.head = Some(new_node);
            }
            Some(ref mut current) => {
                let mut ptr = current.as_mut();
                while let Some(ref mut next) = ptr.next {
                    ptr = next.as_mut();
                }
                ptr.next = Some(new_node);
            }
        }
    }

    pub fn to_vec(&self) -> Vec<String> {
        let mut result = Vec::new();
        let mut current = &self.head;
        while let Some(node) = current {
            result.push(node.value.clone());
            current = &node.next;
        }
        result
    }
}
