// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

mod calculator;
mod cli;
mod evaluator;
mod functions;
mod linked_list;
mod operator;
mod repl;
mod shunting_yard;
mod token;

use std::process;

use clap::Parser;
use cli::Cli;

/// Print help for mathematical functions
fn print_functions_help() {
    println!("Mathematical Functions:");
    println!();
    println!("  lg(x)              Base-10 logarithm");
    println!("  lg(x, base)        Custom base logarithm");
    println!("  log(x, base)       Custom base logarithm (alias)");
    println!("  ln(x)              Natural logarithm (base e)");
    println!("  sqrt(x)            Square root");
    println!("  pow(x, y)          Power function (x^y)");
    println!("  sin(x)             Sine (x in radians)");
    println!("  cos(x)             Cosine (x in radians)");
    println!("  tan(x)             Tangent (x in radians)");
    println!("  asin(x)            Inverse sine (result in radians)");
    println!("  acos(x)            Inverse cosine (result in radians)");
    println!("  atan(x)            Inverse tangent (result in radians)");
    println!("  mod(a, b)          Modulo (a % b)");
}

/// Print help for operators
fn print_operators_help() {
    println!("Operators:");
    println!();
    println!("  Standard Operators:");
    println!("    +    Addition           3 + 2 = 5");
    println!("    -    Subtraction        5 - 2 = 3");
    println!("    *    Multiplication     3 * 4 = 12");
    println!("    /    Division          10 / 2 = 5");
    println!("    %    Modulo            10 % 3 = 1");
    println!("    ^    Exponentiation     2 ^ 3 = 8");
    println!();
    println!("  Bitwise Operators (use -B flag):");
    println!("    &    AND               12 & 10 = 8");
    println!("    |    OR                12 | 10 = 14");
    println!("    ^    XOR               12 ^ 10 = 6");
    println!("    ~    NOT               ~0 = -1");
    println!("    <<   Left shift        8 << 2 = 32");
    println!("    >>   Right shift       8 >> 2 = 2");
}

/// Print help for number formats
fn print_formats_help() {
    println!("Number Formats:");
    println!();
    println!("  Input Formats:");
    println!("    Decimal     255, -456, 3.14");
    println!("    Binary      0b1010, 0b11111111");
    println!("    Octal       0o755, 0o377");
    println!("    Hexadecimal 0xFF, 0x1A");
    println!("    Scientific  1e3, 2.5e-3, 1.23E+10");
    println!();
    println!("  Output Format Options:");
    println!("    -x, --hex   Hexadecimal output  (e.g., 0xFF)");
    println!("    -o, --oct   Octal output        (e.g., 0o377)");
    println!("    -b, --bin   Binary output       (e.g., 0b11111111)");
}

/// Print help for constants
fn print_constants_help() {
    println!("Mathematical Constants:");
    println!();
    println!("  pi, PI    π ≈ 3.141592653589793  (ratio of circumference to diameter)");
    println!("  e, E      e ≈ 2.718281828459045  (Euler's number, natural log base)");
}

/// Print all help information
fn print_all_help() {
    print_operators_help();
    println!();
    print_functions_help();
    println!();
    print_constants_help();
    println!();
    print_formats_help();
}

/// Format and print result based on output format flags
fn print_result(result: f64, hex: bool, oct: bool, bin: bool) -> Result<(), String> {
    if hex || oct || bin {
        if result.fract() == 0.0 && result.abs() < 1e15 {
            let int_val = result as i64;
            if hex {
                if int_val < 0 {
                    println!("= -0x{:X}", int_val.unsigned_abs());
                } else {
                    println!("= 0x{:X}", int_val as u64);
                }
            } else if oct {
                if int_val < 0 {
                    println!("= -0o{:o}", int_val.unsigned_abs());
                } else {
                    println!("= 0o{:o}", int_val as u64);
                }
            } else if bin {
                if int_val < 0 {
                    println!("= -0b{:b}", int_val.unsigned_abs());
                } else {
                    println!("= 0b{:b}", int_val as u64);
                }
            }
            Ok(())
        } else {
            Err("Base output only supports integer results".to_string())
        }
    } else if result.fract() == 0.0 && result.abs() < 1e15 {
        println!("{}", result as i64);
        Ok(())
    } else {
        println!("{}", result);
        Ok(())
    }
}

/// Format and print bitwise result based on output format flags
fn print_bitwise_result(result: i64, hex: bool, oct: bool, bin: bool) {
    if hex {
        if result < 0 {
            println!("= -0x{:X}", result.unsigned_abs());
        } else {
            println!("= 0x{:X}", result as u64);
        }
    } else if oct {
        if result < 0 {
            println!("= -0o{:o}", result.unsigned_abs());
        } else {
            println!("= 0o{:o}", result as u64);
        }
    } else if bin {
        if result < 0 {
            println!("= -0b{:b}", result.unsigned_abs());
        } else {
            println!("= 0b{:b}", result as u64);
        }
    } else {
        println!("{}", result);
    }
}

fn main() {
    let cli = Cli::parse();

    // Handle help display commands
    match cli.command {
        Some(cli::Commands::Functions) => {
            print_functions_help();
            return;
        }
        Some(cli::Commands::Operators) => {
            print_operators_help();
            return;
        }
        Some(cli::Commands::Formats) => {
            print_formats_help();
            return;
        }
        Some(cli::Commands::Constants) => {
            print_constants_help();
            return;
        }
        Some(cli::Commands::Info) => {
            print_all_help();
            return;
        }
        None => {}
    }

    // Handle flag-based help
    if cli.show_functions {
        print_functions_help();
        return;
    }

    if cli.show_operators {
        print_operators_help();
        return;
    }

    if cli.show_formats {
        print_formats_help();
        return;
    }

    if cli.show_constants {
        print_constants_help();
        return;
    }

    // Handle expression calculation
    if let Some(expr) = cli.expression.or(cli.row) {
        if cli.bits {
            // Bitwise mode
            match calculator::calculate_bitwise(&expr) {
                Ok(result) => print_bitwise_result(result, cli.hex, cli.oct, cli.bin),
                Err(e) => {
                    eprintln!("Error: {}", e);
                    process::exit(1);
                }
            }
        } else {
            // Standard mode
            match calculator::calculate(&expr) {
                Ok(result) => {
                    if let Err(e) = print_result(result, cli.hex, cli.oct, cli.bin) {
                        eprintln!("Error: {}", e);
                        process::exit(1);
                    }
                }
                Err(e) => {
                    eprintln!("Error: {}", e);
                    process::exit(1);
                }
            }
        }
        return;
    }

    // Interactive mode
    if cli.bits {
        repl::run_repl_bitwise();
    } else {
        repl::run_repl();
    }
}
