// Ralqlator - A command line calculator
//
// Copyright (C) 2026 Ralqlator Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// AI-Generated Notice: This source file was entirely generated by
// qwen3.5-plus (Alibaba's large language model).

//! Tokenizer module - split input string into tokens
//!
//! Supports:
//! - Scientific notation (e.g., 1e3, 2.5e-3)
//! - Number prefixes: 0b (binary), 0o (octal), 0x (hex)
//! - Constants: C_PI, C_E (using C_xx format)
//! - Bitwise operators in bitwise mode

use crate::operator::{is_function, is_operator};

/// Check if a token is a reserved constant identifier (C_xx format)
pub fn is_constant_identifier(token: &str) -> bool {
    token.starts_with("C_") && token.len() > 2
}

/// Validate constant identifier and return its value
pub fn get_constant_value(token: &str) -> Option<f64> {
    match token {
        "C_PI" | "C_pi" => Some(std::f64::consts::PI),
        "C_E" | "C_e" => Some(std::f64::consts::E),
        _ => None,
    }
}

/// Check if a name conflicts with reserved constant format (C_xx)
/// All C_ prefixed names are reserved for potential future constants
pub fn is_reserved_constant_name(name: &str) -> bool {
    is_constant_identifier(name)
}

/// Tokenize input string into numbers and operators
pub fn tokenize(input: &str, bitwise_mode: bool) -> Vec<String> {
    let mut tokens = Vec::new();
    let mut current = String::new();
    let mut chars = input.chars().peekable();

    while let Some(c) = chars.next() {
        match c {
            c if c.is_whitespace() => push_current(&mut tokens, &mut current),
            '(' | ')' | ',' => {
                push_current(&mut tokens, &mut current);
                tokens.push(c.to_string());
            }
            _ if bitwise_mode => {
                if handle_bitwise_char(c, &mut chars, &mut tokens, &mut current) {
                    continue;
                }
                handle_standard_char(c, &mut chars, &mut tokens, &mut current);
            }
            _ => handle_standard_char(c, &mut chars, &mut tokens, &mut current),
        }
    }

    if !current.is_empty() {
        tokens.push(current);
    }
    tokens
}

/// Push current token if not empty
#[inline]
fn push_current(tokens: &mut Vec<String>, current: &mut String) {
    if !current.is_empty() {
        tokens.push(std::mem::take(current));
    }
}

/// Handle bitwise mode specific characters
/// Returns true if the character was handled
fn handle_bitwise_char(
    c: char,
    chars: &mut std::iter::Peekable<std::str::Chars>,
    tokens: &mut Vec<String>,
    current: &mut String,
) -> bool {
    match c {
        '<' | '>' => {
            if chars.peek() == Some(&c) {
                chars.next();
                push_current(tokens, current);
                tokens.push(format!("{}{}", c, c));
                return true;
            }
        }
        '~' | '&' | '|' | '^' => {
            push_current(tokens, current);
            tokens.push(c.to_string());
            return true;
        }
        _ => {}
    }
    false
}

/// Handle standard character processing
fn handle_standard_char(
    c: char,
    chars: &mut std::iter::Peekable<std::str::Chars>,
    tokens: &mut Vec<String>,
    current: &mut String,
) {
    match c {
        'e' | 'E' => {
            // Check if this is part of C_E constant (C_ followed by e/E)
            if current == "C_" {
                current.push(c);
            } else if is_scientific_notation(current) {
                current.push(c);
            } else {
                push_current(tokens, current);
                tokens.push(c.to_string());
            }
        }
        '+' | '-' | '!' => {
            if c == '!' {
                // Factorial operator
                push_current(tokens, current);
                tokens.push(c.to_string());
            } else if is_scientific_sign(current) {
                current.push(c);
            } else if c == '-' && is_unary_context(tokens, current) {
                // Check if next character is a prefix indicator (0 followed by b/o/x)
                // If so, we'll handle the error in resolve_constants
                push_current(tokens, current);
                tokens.push("-".to_string());
            } else {
                push_current(tokens, current);
                tokens.push(c.to_string());
            }
        }
        '<' | '>' => {
            // Comparison operators
            push_current(tokens, current);
            tokens.push(c.to_string());
        }
        '=' => {
            // Check for == (double equals)
            if chars.peek() == Some(&'=') {
                chars.next();
                push_current(tokens, current);
                tokens.push("==".to_string());
            } else {
                // Single = for equality check (returns yes/no)
                push_current(tokens, current);
                tokens.push("=".to_string());
            }
        }
        '.' => current.push(c),
        c if c.is_ascii_digit() => current.push(c),
        'b' | 'B' | 'o' | 'O' | 'x' | 'X' => {
            if current == "0" || current == "-0" {
                current.push(c.to_ascii_lowercase());
            } else if current.is_empty() || current.chars().all(|ch| ch.is_alphabetic()) {
                current.push(c);
            } else {
                push_current(tokens, current);
                tokens.push(c.to_string());
            }
        }
        c if c.is_alphabetic() || c == '_' => current.push(c),
        c if is_operator(&c.to_string()) => {
            push_current(tokens, current);
            tokens.push(c.to_string());
        }
        _ => {
            push_current(tokens, current);
        }
    }
}

/// Check if 'e' or 'E' is part of scientific notation
#[inline]
fn is_scientific_notation(current: &str) -> bool {
    !current.is_empty() && current.chars().all(|ch| ch.is_ascii_digit() || ch == '.')
}

/// Check if '+' or '-' is part of scientific notation sign
#[inline]
fn is_scientific_sign(current: &str) -> bool {
    !current.is_empty() && matches!(current.chars().last(), Some('e' | 'E'))
}

/// Check if minus sign is in unary context
/// Unary context means the minus is for negation, not subtraction
fn is_unary_context(tokens: &[String], current: &str) -> bool {
    // If current is not empty and contains a number, minus is binary (subtraction)
    // Exception: scientific notation like 1e-3 is handled separately by is_scientific_sign
    if !current.is_empty() {
        return false;
    }
    // If current is empty, check if we're after an operator, opening paren, comma, or function
    tokens
        .last()
        .is_none_or(|last| is_operator(last) || *last == "(" || *last == "," || is_function(last))
}

/// Convert special constants and prefixed numbers to their values
/// Constants use C_xx format (e.g., C_PI, C_E)
/// Note: Negative non-decimal numbers (e.g., -0xFF) are NOT supported
///       Use unary minus instead: -(0xFF)
pub fn resolve_constants(tokens: Vec<String>) -> Result<Vec<String>, String> {
    let mut result = Vec::new();
    let mut i = 0;
    
    while i < tokens.len() {
        let token = &tokens[i];
        
        // Check for unary minus followed by prefixed number
        if token == "-" && i + 1 < tokens.len() {
            let next_token = &tokens[i + 1];
            if next_token.starts_with("0b") || next_token.starts_with("0o") || next_token.starts_with("0x") {
                return Err(format!(
                    "Negative non-decimal numbers are not supported. Use parentheses: -({})",
                    next_token
                ));
            }
        }
        
        if let Some(value) = get_constant_value(token) {
            result.push(value.to_string());
        } else if let Some(parse_result) = parse_prefixed_number(token) {
            result.push(parse_result?.to_string());
        } else {
            result.push(token.clone());
        }
        
        i += 1;
    }
    
    Ok(result)
}

/// Parse numbers with prefixes: 0b (binary), 0o (octal), 0x (hex)
/// Returns None for non-prefixed numbers (they are handled elsewhere)
/// Returns Err for negative prefixed numbers (not supported)
fn parse_prefixed_number(token: &str) -> Option<Result<f64, String>> {
    let (prefix_len, radix) = get_prefix_info(token)?;
    
    // Check for negative prefixed numbers (not supported)
    if token.starts_with('-') {
        return Some(Err(format!(
            "Negative non-decimal numbers are not supported. Use unary minus instead: -(0x{:})",
            &token[prefix_len..]
        )));
    }
    
    let num_str = &token[prefix_len..];

    Some(Ok(i64::from_str_radix(num_str, radix).ok().map(|v| v as f64)?))
}

/// Get prefix length and radix for prefixed numbers
/// Only recognizes positive prefixed numbers (0b, 0o, 0x)
fn get_prefix_info(token: &str) -> Option<(usize, u32)> {
    if token.starts_with("0b") {
        Some((2, 2))
    } else if token.starts_with("0o") {
        Some((2, 8))
    } else if token.starts_with("0x") {
        Some((2, 16))
    } else {
        None
    }
}
